spring:
  data:
    mongodb:
      uri: mongodb+srv://arpitpandey639344:CEZ1ff3LcvLYOXIl@cluster0.obyq0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: taskManager
      auto-index-creation: true

